openapi: 3.0.0
info:
  description: Event Management API
  title: Service sample
  version: "1.0.0"

servers:
  - url: uservice-sample.yandex.net
    description: production
  - url: uservice-sample.tst.yandex.net
    description: testing

paths:
  /users:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../definitions/users.yaml#/components/schemas/UserCreateRequestBody"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "../definitions/users.yaml#/components/schemas/User"
        409:
          description: User already exists
    get:
      parameters:
        - name: email
          in: query
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "../definitions/users.yaml#/components/schemas/User"
        404:
          description: Not found

  /users/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../definitions/users.yaml#/components/schemas/UserLoginRequestBody"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "../definitions/users.yaml#/components/schemas/UserLoginResponseBody"
        401:
          description: Unauthorized
  
  /users/{name_surname}:
    get:
      parameters:
        - name: name_surname
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "../definitions/users.yaml#/components/schemas/User"
  
  /talks:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../definitions/talks.yaml#/components/schemas/CreateTalkRequestBody"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "../definitions/talks.yaml#/components/schemas/Talk"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "../definitions/talks.yaml#/components/schemas/Talk"

  /events:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../definitions/events.yaml#/components/schemas/CreateEventRequestBody"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "../definitions/events.yaml#/components/schemas/Event"
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "../definitions/events.yaml#/components/schemas/Event"
  
  /events/{event_id}/talks:
    get:
      parameters:
        - name: event_id
          in: path
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "../definitions/talks.yaml#/components/schemas/Talk"